version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shazam-service
      POSTGRES_USER: shazam-user
#      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
